name: Update Version

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check outdated dependencies
        run: npm outdated || true

      - name: Update dependencies
        run: npm update 

      - name: Run custom update script
        run: node update.js

      - name: Commit and push changes to develop and master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update dependencies"
            # Push to develop branch
            git push origin develop
            # Push to master branch
            git push origin master
          fi
