name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check outdated dependencies
        run: npm outdated || true

      - name: Update dependencies
        run: npm update 

      - name: Update package.json version
        run: |
          # Usa jq para actualizar la versión
          # Asegúrate de que jq esté instalado; se instala en la imagen de ubuntu-latest por defecto
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current version is $CURRENT_VERSION"
          # Incrementa la versión (aquí se incrementa el patch version, ajusta según sea necesario)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
          jq --arg newVersion "$NEW_VERSION" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json
          echo "Updated version to $NEW_VERSION"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update dependencies"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          fi
